#!/usr/bin/env bash
# CieloOS animated install screen for the terminal. A long install is mostly apt
# and podman noise that nobody reads and that makes a working install look like a
# fault. This puts a curtain over it: the real output goes to a log, and the
# screen shows the system assembling itself, one box per install step.
#
#   ./cielo-install-tui.sh start [logfile]   take over the screen
#   ./cielo-install-tui.sh set <step> <msg>  move to step <step> of 9
#   ./cielo-install-tui.sh env <text>        fill in the runtime box (mode/bind)
#   ./cielo-install-tui.sh stop [ok|fail]    hand the screen back
#
# The counterpart to cielo-install-ui.sh, which does the same job in a browser.
# That one is nicer, but needs a browser; this one works on tty1 of a machine
# that has not got a UI yet. Pure sugar — the install works fine without it.
#
# Frames come from distro/scripts/cielo-install-frames/, generated by ASCII
# Motion (see cielo-install-frames/README.md). Nine stages, twelve frames each.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAME_DIR="${CIELO_TUI_FRAMES:-$HERE/cielo-install-frames}"
STATE="${CIELO_TUI_STATE:-/tmp/cielo-install-tui.state}"
ENVFILE="${CIELO_TUI_STATE:-/tmp/cielo-install-tui.state}.env"
PIDFILE=/tmp/cielo-install-tui.pid
LOGREF=/tmp/cielo-install-tui.log

TOTAL=9
ART_W=80
ART_H=20
FPS="${CIELO_TUI_FPS:-10}"

# The animation is decoration. If there is no terminal to draw on, or the
# terminal cannot do colour, every command here turns into a no-op and the
# installer prints normally.
usable() {
  [[ -t 1 || -e /dev/tty ]] || return 1
  [[ "${TERM:-dumb}" != "dumb" ]] || return 1
  [[ -d "$FRAME_DIR" ]] || return 1
  [[ "${CIELO_TUI:-1}" != "0" ]] || return 1
}

# ── drawing ────────────────────────────────────────────────────────────────
player() {
  exec >/dev/tty 2>/dev/null
  local cols lines pad top stage=0 loaded=-1 i=0 frames=() label='' pct=0

  # a fd we can `read -t` against, so the frame delay costs no forks
  exec 9<> <(:) || true

  snooze() { read -t "$1" -u 9 _ 2>/dev/null || true; }

  measure() {
    cols=$(tput cols 2>/dev/null || echo 80)
    lines=$(tput lines 2>/dev/null || echo 24)
    pad=$(((cols - ART_W) / 2))
    ((pad < 0)) && pad=0
    top=$(((lines - (ART_H + 4)) / 2))
    ((top < 0)) && top=0
    loaded=-1 # force a reload so the new padding is applied
    printf '\033[2J'
  }
  trap measure WINCH
  measure

  local padstr=''
  while :; do
    # state: "<step>|<label>"
    if [[ -r "$STATE" ]]; then
      IFS='|' read -r stage label <"$STATE" || true
    fi
    [[ "$stage" =~ ^[0-9]+$ ]] || stage=1
    ((stage < 1)) && stage=1
    ((stage > TOTAL)) && stage=$TOTAL

    if [[ "$stage" != "$loaded" ]]; then
      printf -v padstr '%*s' "$pad" ''
      if [[ -r "$FRAME_DIR/stage-$stage.ans" ]]; then
        mapfile -d $'\f' -t frames <"$FRAME_DIR/stage-$stage.ans"
        # bake the left margin in once per stage rather than once per frame
        local k
        for k in "${!frames[@]}"; do
          frames[k]="$padstr${frames[k]//$'\n'/$'\n'$padstr}"
        done
      fi
      loaded="$stage"
      i=0
      printf '\033[2J'
    fi
    ((${#frames[@]})) || {
      snooze 0.5
      continue
    }

    printf '\033[%d;1H%s' "$((top + 1))" "${frames[i % ${#frames[@]}]}"

    # the environment line the installer knows and the frames could not
    if [[ -s "$ENVFILE" ]]; then
      local envtext
      read -r envtext <"$ENVFILE" || true
      if [[ -n "$envtext" && "$stage" -ge 6 ]]; then
        local ex=$((pad + 24 + (32 - ${#envtext}) / 2))
        printf '\033[%d;%dH\033[38;5;231m%s\033[0m' \
          "$((top + 1 + 12))" "$((ex + 1))" "$envtext"
      fi
    fi

    pct=$((stage * 100 / TOTAL))
    status "$((top + ART_H + 2))" "$pad" "$stage" "$label" "$pct"

    i=$((i + 1))
    snooze "$(awk -v f="$FPS" 'BEGIN{printf "%.3f", 1/f}')"
  done
}

# Step line, bar, and where the real output went.
status() {
  local row=$1 pad=$2 stage=$3 label=$4 pct=$5
  local barw=56
  local fill=$((pct * barw / 100))
  local bar='' i
  for ((i = 0; i < fill; i++)); do bar+='█'; done
  local rest=''
  for ((i = fill; i < barw; i++)); do rest+='░'; done

  printf '\033[%d;%dH\033[38;5;141m  [%d/%d]\033[0m  \033[38;5;189m%s\033[0m\033[K' \
    "$((row + 1))" "$((pad + 1))" "$stage" "$TOTAL" "$label"
  printf '\033[%d;%dH  \033[38;5;141m%s\033[38;5;60m%s\033[0m  \033[38;5;189m%d%%\033[0m\033[K' \
    "$((row + 2))" "$((pad + 1))" "$bar" "$rest" "$pct"
  local logline=''
  [[ -s "$LOGREF" ]] && read -r logline <"$LOGREF"
  [[ -n "$logline" ]] &&
    printf '\033[%d;%dH  \033[38;5;60mfull log: %s\033[0m\033[K' \
      "$((row + 3))" "$((pad + 1))" "$logline"
}

# ── commands ───────────────────────────────────────────────────────────────
case "${1:-}" in
  start)
    usable || exit 0
    [[ -f "$PIDFILE" ]] && "$0" stop >/dev/null 2>&1
    printf '%s' "${2:-}" >"$LOGREF"
    printf '1|Dependencies' >"$STATE"
    : >"$ENVFILE"
    # alternate screen buffer, so the scrollback the user had is untouched and
    # comes straight back on stop
    printf '\033[?1049h\033[?25l\033[2J' >/dev/tty
    player &
    echo $! >"$PIDFILE"
    ;;

  set)
    usable || exit 0
    printf '%s|%s' "${2:?step}" "${3:-}" >"$STATE"
    ;;

  env)
    usable || exit 0
    printf '%s' "${2:-}" >"$ENVFILE"
    ;;

  demo)
    # Walk the nine steps on a timer so the screen can be reviewed without
    # standing up a machine: ./cielo-install-tui.sh demo [seconds-per-step]
    usable || { echo "no usable terminal for the demo" >&2; exit 1; }
    per="${2:-2}"
    labels=(
      "Dependencies"
      "Service user 'cielo' + rootless podman"
      "Session images + the search service"
      "Session restart policy"
      "Install to /opt/cielo"
      "Environment"
      "systemd service"
      "Chat UI (Open WebUI against /v1/agent)"
      "Presentation mode: kiosk"
    )
    trap '"$0" stop; exit 0' INT TERM
    "$0" start /var/log/cielo-install.log
    "$0" env "app · 127.0.0.1:5148"
    for n in $(seq 1 $TOTAL); do
      "$0" set "$n" "${labels[n - 1]}"
      sleep "$per"
    done
    sleep "$per"
    "$0" stop
    echo "(demo only — nothing was installed)"
    ;;

  stop)
    if [[ -f "$PIDFILE" ]]; then
      kill "$(cat "$PIDFILE")" 2>/dev/null || true
      wait "$(cat "$PIDFILE")" 2>/dev/null || true
      rm -f "$PIDFILE"
    fi
    if [[ -e /dev/tty ]]; then
      printf '\033[?25h\033[?1049l' >/dev/tty 2>/dev/null || true
    fi
    rm -f "$STATE" "$ENVFILE" "$LOGREF"
    ;;

  *)
    sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 2
    ;;
esac
